"""auto_migration

Revision ID: 4d54cab28cca
Revises: 
Create Date: 2025-08-14 12:54:26.345755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d54cab28cca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ticker')
    )
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_metrics_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['daily_metrics_id'], ['daily_metrics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_metrics_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fundamentals')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
