"""auto_migration

Revision ID: 4f6f362c80f7
Revises: 
Create Date: 2025-10-11 12:22:24.700885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6f362c80f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_ticker', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('trade_date',
    sa.Column('trade_date_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('trade_date_id'),
    sa.UniqueConstraint('trade_date_id')
    )
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['trade_date_id'], ['trade_date.trade_date_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('trade_date_id', 'company_id')
    )
    op.create_table('fundamentals',
    sa.Column('daily_metrics_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['daily_metrics_id'], ['daily_metrics.id'], ),
    sa.PrimaryKeyConstraint('daily_metrics_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fundamentals')
    op.drop_table('daily_metrics')
    op.drop_table('trade_date')
    op.drop_table('company')
    # ### end Alembic commands ###
