"""auto_migration

Revision ID: 955d17a25993
Revises: 4f6f362c80f7
Create Date: 2025-10-11 12:24:07.022021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955d17a25993'
down_revision = '4f6f362c80f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['company_id'])
    op.create_unique_constraint(None, 'daily_metrics', ['id'])
    op.create_unique_constraint(None, 'trade_date', ['trade_date_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trade_date', type_='unique')
    op.drop_constraint(None, 'daily_metrics', type_='unique')
    op.drop_constraint(None, 'company', type_='unique')
    # ### end Alembic commands ###
