"""update fundamentals column types

Revision ID: e0735a7e7a24
Revises: 955d17a25993
Create Date: 2025-10-11 19:40:20.740166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0735a7e7a24'
down_revision = '955d17a25993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fundamentals', 'open_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('fundamentals', 'high_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('fundamentals', 'close_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('fundamentals', 'low_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('fundamentals', 'volume',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fundamentals', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('fundamentals', 'low_price',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('fundamentals', 'close_price',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('fundamentals', 'high_price',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('fundamentals', 'open_price',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
