name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: taro_user
          POSTGRES_PASSWORD: taro_password
          POSTGRES_DB: taro_stock
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U taro_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -U taro_user; do sleep 1; done
      - name: Run tests
        env:
          DB_HOST: localhost
          DB_USER: taro_user
          DB_PASSWORD: taro_password
          DB_NAME: taro_stock
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m alembic upgrade head
          pytest tests/ -v

      - name: Start analysis service for testing
        env:
          DB_HOST: localhost
          DB_USER: taro_user
          DB_PASSWORD: taro_password
          DB_NAME: taro_stock
        run: |
          analysis &
          sleep 5
          curl -f http://localhost:5001/health || exit 1
